import os
from dotenv import load_dotenv

load_dotenv()

class Config:
    SECRET_KEY = os.environ.get('SECRET_KEY') or 'una-clave-secreta-muy-dificil-de-adivinar'
    
    # Configuración de la base de datos
    SQLALCHEMY_DATABASE_URI = os.environ.get('DATABASE_URL') or \
        'sqlite:///' + os.path.join(os.path.abspath(os.path.dirname(__file__)), 'instance', 'db.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False

    # --- Implementando Optimización #5: Carpeta de Subida Única ---
    UPLOAD_FOLDER = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'static', 'uploads')
    
    # --- ELIMINADAS (ya no son necesarias) ---
    # PROJECT_IMAGE_UPLOAD_FOLDER = ...
    # NOTE_IMAGE_UPLOAD_FOLDER = ...
    # CAMINATA_IMAGE_UPLOAD_FOLDER = ...
    # PAGOS_IMAGE_UPLOAD_FOLDER = ...
    # CALENDAR_IMAGE_UPLOAD_FOLDER = ...
    # SONGS_UPLOAD_FOLDER = ...
    # PLAYLIST_COVER_UPLOAD_FOLDER = ...
    # INSTRUCTION_ATTACHMENT_FOLDER = ...
    # MAP_FILES_UPLOAD_FOLDER = ...
    # COVERS_UPLOAD_FOLDER = ...
    # ABOUTUS_IMAGE_UPLOAD_FOLDER = ...
    # UPLOAD_FILES_FOLDER = ...


    # Configuración de Flask-Mail para recuperación de contraseña
    MAIL_SERVER = os.environ.get('MAIL_SERVER', 'smtp.googlemail.com')
    MAIL_PORT = int(os.environ.get('MAIL_PORT', 587))
    MAIL_USE_TLS = os.environ.get('MAIL_USE_TLS', 'true').lower() in ['true', 'on', '1']
    
    MAIL_USERNAME = os.environ.get('MAIL_USERNAME', 'noreply@example.com')
    MAIL_PASSWORD = os.environ.get('MAIL_PASSWORD')
    MAIL_DEFAULT_SENDER = os.environ.get('MAIL_DEFAULT_SENDER') or MAIL_USERNAME
